name = "hono-react-ssr-shadcn-ui"
main = "./src/index.tsx"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2026-03-16"
workers_dev = true
preview_urls = false

[cache]
enabled = true
cross_version_cache = true

[vars]
BLOG_USERNAME="admin"

[secrets]
required = [ "BLOG_PASSWORD" ]

[[d1_databases]]
binding = "DB"
migrations_dir = "drizzle/d1"
migrations_pattern = "drizzle/d1/*/migration.sql"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [ai]
# binding = "AI"
