name = "hono-react-ssr-shadcn-ui"
main = "./src/index.tsx"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2026-03-16"
workers_dev = true
preview_urls = false

[vars]
BLOG_USERNAME="admin"

[secrets]
required = [ "BLOG_PASSWORD" ]

[[kv_namespaces]]
binding = "blog"
id = "8617f8968998499bb3db425063f8f01d"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
